---

- name: Include openstack_network provisioner tasks
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/openstack_network/initiator/provision.yaml"
  when: cloud_vpn_initiator_manage_vpc

- name: Include openstack_router provisioner tasks
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/openstack_router/initiator/provision.yaml"
  when: cloud_vpn_initiator_manage_gw

- name: Include openstack_instance provisioner tasks
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/openstack_instance/initiator/provision.yaml"
