---

- name: Generate responder instance template
  template:
    src: cloud_vpn/provisioners/openstack_instance/responder/provision.j2
    dest: "/tmp/{{ cloud_vpn_name }}-responder-instance.template"

- name: Create responder instance stack
  os_stack:
    cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
    name: "{{ cloud_vpn_name }}-responder-instance-stack"
    template: "/tmp/{{ cloud_vpn_name }}-responder-instance.template"
  register: stack_out

- name: Set cloud_vpn_responder_public_ip fact
  set_fact:
    cloud_vpn_responder_public_ip: "{{ stack_out['stack']['outputs'][0]['output_value'] }}"
