---

- block:
    - name: Get VPC facts
      os_networks_facts:
        cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
        name: "{{ cloud_vpn_responder_vpc_id }}"

    - name: Set responder subnet ID
      set_fact:
        cloud_vpn_responder_subnet_id: "{{ openstack_networks[0]['subnets'][0] }}"

    - name: Generate responder provision template
      template:
        src: openstack/responder/provision_in_existing_vpc.j2
        dest: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"
  when: cloud_vpn_responder_vpc_id is defined

- name: Generate responder provision template
  template:
    src: openstack/responder/provision.j2
    dest: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"
  when: cloud_vpn_responder_vpc_id is not defined

- name: Create responder stack
  os_stack:
    cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
    name: "{{ cloud_vpn_name }}-responder-stack"
    template: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"

- name: Get instance facts
  os_server_facts:
    cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
    server: "{{ cloud_vpn_name }}-responder-instance"
  register: out

- name: Set responder IP fact
  set_fact:
    cloud_vpn_responder_public_ip: "{{ openstack_servers[0]['interface_ip'] }}"

- name: Add responder host
  add_host:
    name: responder
    ansible_host: "{{ cloud_vpn_responder_public_ip }}"
    ansible_user: "{{ cloud_vpn_responder_user }}"
    ansible_connection: "{{ cloud_vpn_responder_ansible_connection }}"
    ansible_network_os: "{{ cloud_vpn_responder_ansible_network_os }}"

- name: Wait for SSH port to be reachable
  wait_for:
    host: "{{ cloud_vpn_responder_public_ip }}"
    port: 22

- name: Pause for SSH daemon to settle and accept connections
  pause:
    seconds: "{{ cloud_vpn_pause_before_config_seconds }}"
