---

- name: Generate responder network template
  template:
    src: cloud_vpn/provisioners/openstack_network/responder/provision.j2
    dest: "/tmp/{{ cloud_vpn_name }}-responder-network.template"

- name: Create responder network stack
  os_stack:
    cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
    name: "{{ cloud_vpn_name }}-responder-network-stack"
    template: "/tmp/{{ cloud_vpn_name }}-responder-network.template"
  register: stack_out

- name: Set cloud_vpn_responder_network_id fact
  set_fact:
    cloud_vpn_responder_network_id: "{{ stack_out['stack']['outputs'][0]['output_value'] }}"

- name: Set cloud_vpn_responder_subnet_id fact
  set_fact:
    cloud_vpn_responder_subnet_id: "{{ stack_out['stack']['outputs'][1]['output_value'] }}"
